name: Formatting with Black

on:
  push:
    branches:
      - actions/black
      - main
jobs:
  
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Apply black
      run: |
        cd ./app
        black .

    - name: Push code
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Black formatting" --allow-empty
        git push
