name: Formatting with Black

on:
  pull_request:
    branches: 
      - main
jobs:
  
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # with:
        # ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Apply black
      run: |
        cd ./app
        black .

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a  --allow-empty --no-verify
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    # - name: Push code
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: Automatic Black formatting

