name: "Create docs"

on:
  push:
    branches:
      - docs/actions
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: ./docs/

    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html/
        allow_empty_commit: true

    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@v4.2.5
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: ./docs/build/html/ # The folder the action should deploy
    #     clean: True
    #     single-commit: True
    #     token: ${{ secrets.GITHUB_TOKEN }}
