name: "Create docs"

on:
  push:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/html/

    # Publish built docs to gh-pages branch.
    # ===============================
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        clean: False
    - run: |
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        git push
